[profile.release]
panic = 'unwind'

[package]
authors = ['Parity Technologies <admin@parity.io>']
build = 'build.rs'
edition = '2018'
name = 'node-template'
version = '0.9.0'

[[bin]]
name = 'template-node'
path = 'src/main.rs'

[dependencies]
error-chain = '0.12'
exit-future = '0.1'
futures = '0.1'
hex-literal = '0.1'
log = '0.4'
parity-codec = '3.0'
parking_lot = '0.7.1'
slog = '^2'
tokio = '0.1'
trie-root = '0.11.0'

[dependencies.basic-authorship]
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-basic-authorship'
rev = 'ebe4c972bab088a760ca43e7662bf750ccf1e919'

[dependencies.consensus]
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-consensus-aura'
rev = 'ebe4c972bab088a760ca43e7662bf750ccf1e919'

[dependencies.ctrlc]
features = ['termination']
version = '3.0'

[dependencies.inherents]
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-inherents'
rev = 'ebe4c972bab088a760ca43e7662bf750ccf1e919'

[dependencies.network]
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-network'
rev = 'ebe4c972bab088a760ca43e7662bf750ccf1e919'

[dependencies.node-executor]
git = 'https://github.com/paritytech/substrate.git'
rev = 'ebe4c972bab088a760ca43e7662bf750ccf1e919'

[dependencies.node-template-runtime]
path = 'runtime'

[dependencies.primitives]
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-primitives'
rev = 'ebe4c972bab088a760ca43e7662bf750ccf1e919'

[dependencies.sr-io]
git = 'https://github.com/paritytech/substrate.git'
rev = 'ebe4c972bab088a760ca43e7662bf750ccf1e919'

[dependencies.substrate-cli]
git = 'https://github.com/paritytech/substrate.git'
rev = 'ebe4c972bab088a760ca43e7662bf750ccf1e919'

[dependencies.substrate-client]
git = 'https://github.com/paritytech/substrate.git'
rev = 'ebe4c972bab088a760ca43e7662bf750ccf1e919'

[dependencies.substrate-executor]
git = 'https://github.com/paritytech/substrate.git'
rev = 'ebe4c972bab088a760ca43e7662bf750ccf1e919'

[dependencies.substrate-service]
git = 'https://github.com/paritytech/substrate.git'
rev = 'ebe4c972bab088a760ca43e7662bf750ccf1e919'

[dependencies.transaction-pool]
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-transaction-pool'
rev = 'ebe4c972bab088a760ca43e7662bf750ccf1e919'

[build-dependencies]
vergen = '3'
